export type PaperSpecs = {
  gsm: number;
  quality: string;
};

export type JobSize = {
  width: number;
  height: number;
};

export type MasterSheetSize = {
  width: number;
  height: number;
};

export type InventorySuggestion = {
  masterSheetSizeWidth: number;
  masterSheetSizeHeight: number;
  wastagePercentage: number;
  sheetsPerMasterSheet: number;
  totalMasterSheetsNeeded: number;
};

export type JobCardData = {
  id?: string; 
  jobCardNumber?: string; // Unique job card number, generated by system
  date: string; 
  jobName: string;
  customerName: string;
  jobSizeWidth: number;
  jobSizeHeight: number;
  masterSheetSizeWidth?: number; 
  masterSheetSizeHeight?: number; 
  netQuantity: number;
  grossQuantity: number;
  paperGsm: number;
  paperQuality: string;
  wastagePercentage?: number; 

  kindOfJob: 'METPET' | 'NORMAL' | 'NO_PRINTING' | '';
  printingFront: 'SM74' | 'SORSZ' | 'DOMINANT' | 'NO_PRINTING' | '';
  printingBack: 'SM74' | 'SORSZ' | 'DOMINANT' | 'NO_PRINTING' | '';
  coating: 'TEXTURE_UV' | 'VARNISH_GLOSS' | 'VARNISH_MATT' | 'UV_ONLY' | 'NO_COATING' | '';
  specialInks?: string; 
  die: 'NEW' | 'OLD' | '';
  assignedDieMachine?: 'Machine1' | 'Machine2' | 'Machine3' | 'Machine4' | '';
  hotFoilStamping: 'GOLDEN' | 'SILVER' | 'COPPER' | 'NO_LEAF' | '';
  emboss: 'YES' | 'NO' | '';
  pasting: 'YES' | 'NO' | '';
  boxMaking: 'MACHINE' | 'MANUAL' | 'COMBINED' | '';
  remarks?: string;
  dispatchDate?: string;

  linkedJobCardIds?: string[];
  currentDepartment?: string;
  status?: string; 
  createdAt?: string;
  updatedAt?: string;
};

export type JobTemplate = {
  id: string;
  name: string;
  kindOfJob?: JobCardData['kindOfJob'];
  printingFront?: JobCardData['printingFront'];
  printingBack?: JobCardData['printingBack'];
  coating?: JobCardData['coating'];
  die?: JobCardData['die'];
  hotFoilStamping?: JobCardData['hotFoilStamping'];
  emboss?: JobCardData['emboss'];
  pasting?: JobCardData['pasting'];
  boxMaking?: JobCardData['boxMaking'];
};

// For form validation
import { z } from 'zod';

export const JobCardSchema = z.object({
  jobName: z.string().min(1, "Job name is required"),
  customerName: z.string().min(1, "Customer name is required"),
  
  jobSizeWidth: z.coerce.number().positive("Job width must be positive"),
  jobSizeHeight: z.coerce.number().positive("Job height must be positive"),
  
  netQuantity: z.coerce.number().positive("Net quantity must be positive"),
  grossQuantity: z.coerce.number().positive("Gross quantity must be positive"),
  
  paperGsm: z.coerce.number().positive("Paper GSM must be positive"),
  paperQuality: z.string().min(1, "Paper quality is required"),

  masterSheetSizeWidth: z.coerce.number().optional(),
  masterSheetSizeHeight: z.coerce.number().optional(),
  wastagePercentage: z.coerce.number().optional(),

  kindOfJob: z.enum(['METPET', 'NORMAL', 'NO_PRINTING', '']).optional(),
  printingFront: z.enum(['SM74', 'SORSZ', 'DOMINANT', 'NO_PRINTING', '']).optional(),
  printingBack: z.enum(['SM74', 'SORSZ', 'DOMINANT', 'NO_PRINTING', '']).optional(),
  coating: z.enum(['TEXTURE_UV', 'VARNISH_GLOSS', 'VARNISH_MATT', 'UV_ONLY', 'NO_COATING', '']).optional(),
  specialInks: z.string().optional(),
  die: z.enum(['NEW', 'OLD', '']).optional(),
  assignedDieMachine: z.enum(['Machine1', 'Machine2', 'Machine3', 'Machine4', '']).optional(),
  hotFoilStamping: z.enum(['GOLDEN', 'SILVER', 'COPPER', 'NO_LEAF', '']).optional(),
  emboss: z.enum(['YES', 'NO', '']).optional(),
  pasting: z.enum(['YES', 'NO', '']).optional(),
  boxMaking: z.enum(['MACHINE', 'MANUAL', 'COMBINED', '']).optional(),
  remarks: z.string().optional(),
  dispatchDate: z.string().optional(), // Assuming date string, can be refined with z.date() if needed
});

export type JobCardFormValues = z.infer<typeof JobCardSchema>;

export const KINDS_OF_JOB_OPTIONS = [
  { value: 'METPET', label: 'MetPet' },
  { value: 'NORMAL', label: 'Normal' },
  { value: 'NO_PRINTING', label: 'No Printing' },
] as const;

export const PRINTING_MACHINE_OPTIONS = [
  { value: 'SM74', label: 'SM74' },
  { value: 'SORSZ', label: 'SORSZ' },
  { value: 'DOMINANT', label: 'Dominant' },
  { value: 'NO_PRINTING', label: 'No Printing' },
] as const;

export const COATING_OPTIONS = [
  { value: 'TEXTURE_UV', label: 'Texture UV' },
  { value: 'VARNISH_GLOSS', label: 'Varnish Gloss' },
  { value: 'VARNISH_MATT', label: 'Varnish Matt' },
  { value: 'UV_ONLY', label: 'UV Only' },
  { value: 'NO_COATING', label: 'No Coating' },
] as const;

export const DIE_OPTIONS = [
  { value: 'NEW', label: 'New' },
  { value: 'OLD', label: 'Old' },
] as const;

export const DIE_MACHINE_OPTIONS = [
  { value: 'Machine1', label: 'Die Machine 1' },
  { value: 'Machine2', label: 'Die Machine 2' },
  { value: 'Machine3', label: 'Die Machine 3' },
  { value: 'Machine4', label: 'Die Machine 4' },
] as const;

export const HOT_FOIL_OPTIONS = [
  { value: 'GOLDEN', label: 'Golden' },
  { value: 'SILVER', label: 'Silver' },
  { value: 'COPPER', label: 'Copper' },
  { value: 'NO_LEAF', label: 'No Leaf' },
] as const;

export const YES_NO_OPTIONS = [
  { value: 'YES', label: 'Yes' },
  { value: 'NO', label: 'No' },
] as const;

export const BOX_MAKING_OPTIONS = [
  { value: 'MACHINE', label: 'Machine' },
  { value: 'MANUAL', label: 'Manual' },
  { value: 'COMBINED', label: 'Combined' },
] as const;
